AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for aws-serverless-graphql-dynamodb
  
Globals:
  Function:
    Timeout: 3

Resources:
  DemoGraphQLApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod 
  DemoGraphQLFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: graphql-lambda/
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Policies:
        # Give DynamoDB Full Access to your Lambda Function
        - AmazonDynamoDBFullAccess
      Events:
        GraphQLQuery:
          Type: Api
          Properties:
            RestApiId: !Ref DemoGraphQLApi
            Path: /graphql
            Method: post
  DemoDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: demoempdb
      PrimaryKey:
        Name: empId
        Type: Number
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5      
Outputs:
  DemoGraphQLApi:
    Description: "API Gateway endpoint URL for Prod stage for Demo Backend function"
    Value: !Sub "https://${DemoGraphQLApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/graphql/"
  DemoGraphQLFunction:
    Description: "GraphQL Lambda Function ARN"
    Value: !GetAtt DemoGraphQLFunction.Arn

